@startuml
:Empleado:
usecase (Alta cliente)
usecase (Introducir pedido)
usecase (Obtener Estado Pedido)
usecase (Cancelar Pedido)
usecase (Buscar Cliente)
usecase (Pago en cuenta)
usecase (Buscar pedido)
usecase (Pago con tarjeta)
:Empleado: -- (Alta cliente)
:Empleado: -- (Introducir pedido)
:Empleado: -- (Obtener Estado Pedido)
:Empleado: -- (Cancelar Pedido)
:Empleado: -- (Buscar pedido)
(Alta cliente) ..> (Introducir pedido):extiende
(Introducir pedido) ..> (Buscar Cliente):incluye
(Pago con tarjeta) ..>(Introducir pedido):extiende
(Pago en cuenta)..> (Introducir pedido):extiende
(Obtener Estado Pedido)..>(Buscar pedido):incluye
(Cancelar Pedido)..>(Buscar pedido):incluye
@enduml