@startuml
:Socio:
:Biblioteca:
usecase (Reservar Libro)
usecase (Prestar libro)
usecase (Devolver Libro)
usecase (Actualizar catalogo)
:Socio: --(Reservar Libro)
:Socio: --(Prestar libro)
:Socio: -- (Devolver Libro)
:Biblioteca: -- (Prestar libro)
:Biblioteca: -- (Actualizar catalogo)
@enduml